name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run backend
      run: npm run start-be &
    - name: Run frontend
      run: npm run start-fe &
    - name: Run UI tests 
      run: npm run test-ui
